# This workflow will do a rebuild of the docker image and publish to the container registry

name: Build

on:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build & Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        registry: googlescholarregistry.azurecr.io
        name: googlescholarregistry.azurecr.io/gs-scraper
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}